package com.test.viewpagedemo.GreenDao.resource;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.viewpagedemo.GreenDao.Order;
import com.test.viewpagedemo.GreenDao.User;
import com.test.viewpagedemo.GreenDao.Person;

import com.test.viewpagedemo.GreenDao.resource.OrderDao;
import com.test.viewpagedemo.GreenDao.resource.UserDao;
import com.test.viewpagedemo.GreenDao.resource.PersonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig personDaoConfig;

    private final OrderDao orderDao;
    private final UserDao userDao;
    private final PersonDao personDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        personDaoConfig = daoConfigMap.get(PersonDao.class).clone();
        personDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        personDao = new PersonDao(personDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(User.class, userDao);
        registerDao(Person.class, personDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        personDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PersonDao getPersonDao() {
        return personDao;
    }

}
